### ISSUE TITLE
How to put orderby in relationship?

### ISSUE THREAD

**Issue by quinhone** [andersao/l5-repository#66]
I need to bring data from two tables and I need the data come in alphabetical order, but I could only put in the first table, the related table I could not. See example:

table Categories and Table Subcategories

$categories = $this->repository->with(['subcategories'])->scopeQuery(function($query){
    return $query->orderBy('cat_name','asc');
})->all();

but I have to bring also subcategories alphabetically, but I can not

**Comment by CylonSK** [comment]
What about something like this
$categories = $this->repository->with(['subcategories' => function($query){
return $query->orderBy('cat_name','asc');
}])->scopeQuery(function($query){
return $query->orderBy('cat_name','asc');
})->all();

I am not sure if it will works, because I never sucessfuly use this package, but this one should be working.

**Comment by yazfield** [comment]
@CylonSK your answer is correct.

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.
