### ISSUE TITLE
How can I make this query in l5-repository?

### ISSUE THREAD

**Issue by quinhone** [andersao/l5-repository#96]
How can I make this query in l5-repository?

$products  = Produtct::join('products_est', 'products.prod_id', '=', 'products_est.product_id')
            ->join('products_photos', 'products.prod_id', '=', 'products_photos.product_id')
            ->select('*')
            ->where('products_est.prod_est_des_home' ,'=', '1')
            ->where('products_est.prod_est_show_site', '=', '1')
            ->where('products_photos.prod_ft_des', '=', '1')
            ->paginate(24);

**Comment by henninghorn** [comment]
@quinhone 

Take a look at criterias: https://github.com/andersao/l5-repository#create-a-criteria

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by apstyx** [comment]
@quinhone Did you manage to resolve your issue? I am struggling with a very basic join using L5-repository. If you could please paste a full example as everything I have found seems like partial solutions. Thanks in advance

**Comment by quinhone** [comment]
@apstyx I could not, I ended up using the form of Laravel even in these cases.
Product::join()

**Comment by ionut-tanasa** [comment]
I think you could achieve your result with a Criteria. 

Or even create a custom method on your Product repository that uses the underlying model instance to replicate that query.

**Comment by apstyx** [comment]
@ionut-tanasa Agreed a Criteria would work perfect in the case where there is a fixed query. I have not been able to figure how to specify a working criteria with a variable as an input. If you know of this dark magic, please share as it would clean up the code base even more :)

@quinhone I figured this out I think, maybe not perfect but it is working in my case. I have tried to adept it your query. 

Please let me know if it helps

My understanding is that once the repository is accessed one uses the scopeQuery to to attach SQL statements to the basic SELECT * FROM "repositoryName". You need to experiment a little bit certain query additions as I figured out that I could not max or min or normal join, however for your case leftJoin should work a charm. I have added a $randomVariable to the example just in case you want to specify a variable input for the scopeQuery, otherwise remove the use ($randomVariableId).

```
$this->product = $product; // $product is set through a constructor as ProductInterface $product

$products = $this->product->scopeQuery(function ($query) use ($randomVariableId) {
              return $query->leftJoin('products_est', 'products.prod_id', '=', 'products_est.product_id')
                          ->where('products_est.prod_est_des_home' ,'=', '1')
                          ->where('products_est.prod_est_show_site', '=', '1')
                          ->where('products_photos.prod_ft_des', '=', $randomVariableId);
              })->all();

```

**Comment by quinhone** [comment]
@apstyx Very good! Tks!!!
