### ISSUE TITLE
How can I generate a repository for a already create Model?

### ISSUE THREAD

**Issue by isaackearl** [andersao/l5-repository#98]
Accoring to the readme, I can create the model first and then use make:repository to create my repository... unfortunately this doesn't seem to work and tells me my model is already created.  I would really like to generate repositories without overwriting my models.

**Comment by andersao** [comment]
Hi @isaackearl, I will fix this.

**Comment by andersao** [comment]
I've been very busy in recent months with my work projects, which eventually pulling away of my personal projects, so it could not provide the necessary support to you, I am more relaxed now and I'm checking all the issues in order to work on fixes and new implementations, apologize to everyone.

**Comment by Mythos** [comment]
I could also need that, 'cause I'm using the [crud-generator](https://packagist.org/packages/appzcoder/crud-generator) package.

**Comment by k1ng440** [comment]
Hi @andersao, by any chance you got it done yet? 

i am planning to integrate this to exisitng project i have been working for past 2 years.

**Comment by mvpasarel** [comment]
@k1ng440 Put your models path in another folder, Entities or something. Create the repository with new model and change either the model path in repository or update new models with code from existing model. You gain more from using the package instead of just waiting for a fix on that issue.

Feel free to do the change in the package and do a pull-request.

**Comment by cdarken** [comment]
Created pull request #321 for this.
